apiVersion: v2
name: openads-demo-service
version: 2.0.0
appVersion: 2.0.0
description: Demo repository for an OpenADS module
dependencies:
  - repository: oci://ghcr.io/openads-project/openads-helm
    name: openadservice
    version: 1.1.0
